version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/src/files:/app/src/files # Persist the uploads directory
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
